### ISSUE TITLE
Catalina is not supported

### ISSUE THREAD

**Issue by balldk** [godbout/kindaVim.theapp#17]
I found this project "kinda" cool, but my mac using Catalina (version 10.15.7) and it said I can't use this app because it requires version 12.0 or later. Is there any reason not to support older versions? And if so, are you intended to support those in the future? thanks btw

<img width="418" alt="image" src="https://user-images.githubusercontent.com/40964745/146060986-f917ca55-1e24-40e3-b864-080591fab0cc.png">

**Comment by godbout** [comment]
"kinda" ahahhahhahahaha nice one. 

unfortunately no. that's why it's called the *Monterey be'a* on the site. i started developing it on Catalina, then Big Sur. each version has their own bugs that you need to write wrappers for. it's a pain. but the main reasons are 1) i'm not familiar with AppKit and old Apple's technologies 2) the pace at Apple has been quite rapid lately, with Swift and SwiftUI 3) they're deprecating stuff and the way forward is definitely Swift and SwiftUI. so basically it made no sense for me to learn old stuff and doing it the old way when the future is coming. if i had some AppKit skills i may have been able to handle, but it's not the case. i'd rather put my energy of developing what is specific to kindaVim. which is the awesomeness of Vim moves 🚀️🚀️🚀️

**Comment by godbout** [comment]
and i feel your pain. i started kV on a 27 iMac from 2012. stuck on Catalina. i had to retire him. the poor beast is now lying on the floor. literally.

**Comment by balldk** [comment]
haha yeah, I'm actually planning to get a mac M1, so hope to use this app soon. Also, great work and love your humor at README, keep it up :muscle:

**Comment by godbout** [comment]
a new Mac??? M1??? maybe you should be the one finishing this project. ☹️

**Comment by godbout** [comment]
> haha yeah, I'm actually planning to get a mac M1, so hope to use this app soon. Also, great work and love your humor at README, keep it up 💪

and thanks for the humor part but i have no idea what you are talking about.
