### ISSUE TITLE
G doesn't scroll to the bottom

### ISSUE THREAD

**Issue by disrupted** [godbout/kindaVim.theapp#2]
in my short time of testing kV, one issue I noticed upfront is that `G` doesn't scroll to the bottom to the page (similarly how `gg` would scroll to the top). Instead it seems to scroll up a bit (half a page?).

**Comment by godbout** [comment]
@disrupted can you let me know:

1. on which app does this happen
2. if it's text, do you have a block cursor (Accessibility Strategy) or not (Keyboard Strategy)?

thanks!

**Comment by godbout** [comment]
@disrupted ah. glad you're reporting. it shows me that i haven't been clear enough about what kV does.

where kV shines is in input fields. the distinction between the `Accessibility Strategy` and the `Keyboard Strategy` is within input fields. if kV can read the text of an input field, the `Accessibility Strategy` is used, you'll see a block cursor, and in that case we have full control and can apply exact Vim moves. if the text cannot be read, we use the `Keyboard Strategy` and "remap" keys. in the latter case for example `w` would be remapped to `option-right`. it is more wonky.

when you're dealing with non text fields, it will always use the `Keyboard Strategy`, hence remapping keys. so `j` will always be remapped to `down`. (this is not the case for the `Accessibility Strategy`, where there's calculations behind the scenes to place the caret at the same column of the next line.) with the `Keyboard Strategy` `gg` and `G` are atypical in the sense that they are remapped differently depending on the type of fields they're dealing with. for text fields `G` is remapped to `command-down; control-a; option-left; option-right` to go to the first non blank of the last physical line. for non text fields, `G` is remapped to `option-down` to go to the last item of a list, table, etc.

now the issue here is that Safari is an `AXWebArea` and is considered text. `AXWebArea` are what is used for example in email clients when you compose an email. so when you press `G` for Safari it is translated to `command-down; control-a; option-left; option-right`. in Safari for whatever reason `control-a` does a page-up, which is what you're experiencing. Brave works fine. Chrome half. Firefox not at all. because they all use different type of fields and/or custom key mappings.

i'm trying to think of a way to handle consistency in the long term, but i'm not even sure it's possible. my first idea was to have to have lists of key remaps on a PER APPLICATION basis, which is already kinda crazy. but you have apps like `Alfred` where going to the last result item is `fn+down`, while in the Preferences lists use the standard `option+down`. that means we would have to handle key remaps on a PER APPLICATION and PER WINDOW and PER FIELD basis. not worth it. another way to handle consistency is to stop kV for anything else than text inputs. but personally i use `jk` a lot, also Visual Mode to select and delete a bunch of emails together, etc etc.

it may ultimately be that kV will actually not be consistent enough to be interesting or usable. that's what i hope to find out with the beta.

ok finally, for your case, i would suggest having a look at browser extensions like [Vimari](https://github.com/televator-apps/vimari). it brings some Vim moves to Safari, without having to enter any `mode`. it also uses JavaScript so you get smooth scrolling. what kV cannot do. you'll get a better experience than kV for this particular case.

**Comment by godbout** [comment]
i think now that the browsers support will come and allow for the Accessibility Strategy in browsers, i'll make the Keyboard Strategy more straightforward. ultimately i may be able to allow `G` to be mapped to `cmd+down`, which would solve this issue. more later.

**Comment by godbout** [comment]
fixed in beta 6. thanks for the report @disrupted !
