### ISSUE TITLE
:q for quitting app (CMD+Q)

### ISSUE THREAD

**Issue by danymat** [godbout/kindaVim.theapp#24]
Hello, I just downloaded this plugin and I love it so far !

I think it can be interesting to map :q to CMD+Q so that we can quit apps in vim mode. 

EDIT: In the same idea, we could map :w to save in apps (like Pages for example)

**Comment by godbout** [comment]
i like it.

there's some questions also about letting some commands go through kV, like `command q` or `command s`. i'm not sure yet what's the best yet. thinking out loud here. i like `:q` and `:w` because it stays true to Vim, and somehow *locks* the things. like it's clear the separation between macOS itself and kV Modes. question though: what do you think should happen after `:q`? go back to Insert Mode or stay in Normal Mode. (same question for `:w`.)

**Comment by tthkbw** [comment]
:w should say in Normal Mode. You just wanted to save the file, not quit editing in Normal Mode, for example.

:q probably should quit Normal Mode. When you quit, you are leaving whatever context you were working in and will be doing something else--probably don't want Normal Mode then.

**Comment by godbout** [comment]
yeah, so that's my initial feeling too. now the problem i will have implementing this is the following: what if the app you're saving the file from shows the Finder dialog? should it go back to Insert Mode or stay in Normal Mode? kV tracks one load of information per input fields. when you're out of the current input field those info are gone. which is why currently as soon as you leave an input field it switches to Insert Mode (like clicking anywhere). so i'm not sure how to get something consistent here. are the expectations that when you do `:w` it always stay in Normal Mode? or it is ok if sometimes it switches to Insert Mode? to always stay in Normal Mode while switching input fields would require, i think, another project 😂️

**Comment by danymat** [comment]
What about keeping normal mode only if you are in the same window ? If you can count a confirmation prompt (or save dialog) as an other window, then we can escape normal mode

**Comment by godbout** [comment]
that would be my idea yeah. as long as you're in the same *input field*, we keep Normal Mode. if you leave the current *input field*, you're in Insert Mode. just still afraid it's going to be confusing at the end. i'll have a try and see. there's some work to be done first to detect the input field change, so probably in a couple of weeks 👍️

**Comment by godbout** [comment]
done in 1b16: https://github.com/godbout/kindaVim.theapp/releases/tag/1b.16
pretty fun :D thanks for the idea. great one.

**Comment by godbout** [comment]
test suite passed, and it's working fine manually here:

https://user-images.githubusercontent.com/121373/177366177-b9a36ae3-3779-4358-89a6-13a0f2b5ff05.mp4

can you try after rebooting?
also, any other tool that grabs key presses, like Hammerspoon? KE?
also, you don't use kV in the mornings or you found a way to crack it 😄️

**Comment by danymat** [comment]
Indeed I use Hamerspoon and KE. Do I need to remove them for KindaVim to work properly ?

> also, you don't use kV in the mornings or you found a way to crack it

I live in France, that's why ;) (salut !)

**Comment by godbout** [comment]
> Indeed I use Hamerspoon and KE. Do I need to remove them for KindaVim to work properly ?

the issue may be that KE or Hammerspoon are catching the `command q` and doing something with it and/or never passing it along. so kV never receives it. i don't know, just a guess. i'll check on my side, but i don't think anything changed regarding key handling. it's been the same for a while now.

> I live in France, that's why ;) (salut !)

QUOI !? normalement c'est de 5am a 1pm heure locale. ca bloque pas en France le matin ? :D

**Comment by godbout** [comment]
> QUOI !? normalement c'est de 5am a 1pm heure locale. ca bloque pas en France le matin ? :D

checked and it's definitely related to your own current timezone time. if you're able to use it from 5am to 1pm France time, that means there's a bug i can't reproduce. lucky you. enjoy.

**Comment by godbout** [comment]
> i'll check on my side, but i don't think anything changed regarding key handling. it's been the same for a while now.

confirmed. nothing changed on kV's side.

**Comment by danymat** [comment]
> QUOI !? normalement c'est de 5am a 1pm heure locale. ca bloque pas en France le matin ? :D

I posted it at the afternoon :D that's why.
I'm a hacker but I promise did not pwned your application, I'm even considering buying it
