### ISSUE TITLE
Cancelling visual mode

### ISSUE THREAD

**Issue by tthkbw** [godbout/kindaVim.theapp#36]
Using Drafts (well-behaved Mac app??), I use my hotkey to enter normal mode in kv. I then enter visual mode by typing 'v'. I select some text. I realized I just suffered from a brain fart, and don't want to be in visual mode. In Vim, I use <ESC> to exit visual mode. In kv, this doesn't work. If I use <ESC>, I leave kv, but the highlight is still there, which is a problem since beginning to type will delete the highlighted text.

In playing with this, I realized that using 'v' when in visual mode cancels visual mode both in kv and Vim. That is probably sufficient, but I think that if <ESC> is going to make you leave normal mode, it should also unhighlight visual mode selections. It feels wrong to me that highlights stick around when you leave normal mode using <ESC> or the hotkey, particularly since one always has a highlight of at least one character when you leave normal mode.

**Comment by godbout** [comment]
> Using Drafts (well-behaved Mac app??)

nice. didn't know about Drafts. i use iA Writer. i'll forward to the ones who are using Electron shit apps.

> I use my hotkey to enter normal mode in kv. I then enter visual mode by typing 'v'. I select some text. I realized I just suffered from a brain fart, and don't want to be in visual mode. In Vim, I use to exit visual mode. In kv, this doesn't work. If I use , I leave kv, but the highlight is still there, which is a problem since beginning to type will delete the highlighted text.

AH i get it now. that's because you exit Visual Mode with `esc` right? there's nothing about leaving Visual Mode with `esc` in the Vim docs. in practice tho, you get like a one second delay before the selection disappears, and yes it goes back to Normal Mode. in kV currently the way to leave Visual Mode matches Vim, except for that `esc` thing. you use `v` to leave `v`, `V` to leave `V`. but yeah, if Vim allows `esc` even if not in the docs, and people use it this way, i should definitely match Vim. didn't get this before. thanks!

> In playing with this, I realized that using 'v' when in visual mode cancels visual mode both in kv and Vim. That is probably sufficient, but I think that if is going to make you leave normal mode, it should also unhighlight visual mode selections. It feels wrong to me that highlights stick around when you leave normal mode using or the hotkey, particularly since one always has a highlight of at least one character when you leave normal mode.

yes, when in Visual Mode Characterwise (entered with `v`), `v` exists and `V` goes into Visual Mode Linewise. reversed if you entered Visual Mode in Linewise. well i had this `esc` left for me so that i can comment, indent, or run Alfred on the selection left when back in Insert Mode. but yeah for the `esc` you're right. so i'll get myself another shortcut to leave with the selection. thank you! kV is gonna be better now. 

what about leaving with the Keyboard Shortcut you use to enter? there's nothing to match in Vim. like `esc` in Normal Mode shouldn't go back to Insert Mode. what's your thoughts? making it go back to macOS Insert Mode? deactivate it so that you can't leave with that Keyboard Shortcut?

also, for the highlighted text. so i'll change the current `esc` behavior. there's still one case where it'll happen though and i had a look before and it's gonna be a pain to get rid of it. it's when you click somewhere else. like you're in Draft in Normal Mode, and you click on Mail. kV detects the click and goes back to Insert Mode. but macOS informs kV only when the app (Draft) was left already. so there's no easy way to remove the selection. even if i kept a track of the previous apps, that would require to switch back and forth between the new app (Mail), the previous app (Draft), remove the selection, and send back to Mail. that would be kinda shit. what's your thoughts on that one? is leaving the highlight if you click away ok? (like it would happen with any macOS app in normal time if you weren't using kV.)

**Comment by tthkbw** [comment]
With respect to leaving Normal Mode, I think this is a training and understanding issue. Require that leaving kv is done with a key that would enter insert mode in Vim ('i', 'a','c', whatever), or leaving the app you are in (like with mouse click elsewhere, as you describe. One has to remember that kv IS vim, and in vim, the way you leave normal mode is not by <ESC>, but by using 'I' or an equivalent.

**Comment by godbout** [comment]
your messages are so mysterious 😍️ there's always some blank space where i have to let my imagination run wild 😂️😂️😂️

**Comment by godbout** [comment]
> . If I use , I leave kv,

> the way you leave normal mode is not by , but by using 'I' or an equivalent.

😄️

**Comment by godbout** [comment]
funny story. i started working on this and guess what. the implementation is already there and the tests too 😂️😂️😂️ `esc` was just calling Insert Mode with the following comment on top:

```swift
// currently a hack
// so that we can comment multiple lines by keeping the VM selection :D
```

so that was definitely done **deliberately** earlier. it fitted my workflow. i guess you had to punch me enough times about it for me to start remembering 😅️😬️

leaving Normal Mode with the Keyboard Shortcut you used to enter it is still kinda needed if that Shortcut is `esc` tho, as it's the only way i see to send back `esc` to macOS. not needed if your Shortcut is not `esc`. honestly i would have liked to remove the feature entirely as it's gonna create a habit that doesn't match Vim.

**Comment by godbout** [comment]
ok also i'm seeing that for a Custom Keyboard Shortcut, your Shortcut is actually currently a kill switch, and goes back to Insert Mode while leaving the selection intact. to go back to Insert Mode matching Vim you'd need to do `esc` then `i`. i want to leave it like this, so that people can run stuff on the selection (although there's gonna be another general kill switch, for people who enter Normal Mode with `esc`), but also more important to not create bad habits in relation with Vim. you ok with that?

**Comment by tthkbw** [comment]
Oops--I wondered what was weird about my posts. You create this cool glyph for the ESCAPE key and I don't know how to do that. So I used '\<ESC\>'. That shows properly in this Github text field now, because I escaped (!!) the '<' and '>' with '\'. If I don't use the escape, it shows up properly when I type it, but disappears in preview and when posted.

I am relatively new to Github and some of these things seem beyond my ken.

**Comment by tthkbw** [comment]
> ok also i'm seeing that for a Custom Keyboard Shortcut, your Shortcut is actually currently a kill switch, and goes back to Insert Mode while leaving the selection intact. to go back to Insert Mode matching Vim you'd need to do `esc` then `i`. i want to leave it like this, so that people can run stuff on the selection (although there's gonna be another general kill switch, for people who enter Normal Mode with `esc`), but also more important to not create bad habits in relation with Vim. you ok with that?

This confuses me a bit. Currently, if I am in Normal Mode and hit ESCAPE, that action returns me to insert mode with the highlight still active. Typing 'I' then, just replaces the selection with 'I'. 

I had though earlier of suggesting that 'q' be used to quit kv--that is, leave kv and remove the selection. But it didn't seem very Vimmy. Are you suggesting a separate command that would leave kv and deactivate the selection?

**Comment by godbout** [comment]
> Oops--I wondered what was weird about my posts. You create this cool glyph for the ESCAPE key and I don't know how to do that. So I used '<ESC>'. That shows properly in this Github text field now, because I escaped (!!) the '<' and '>' with ''. If I don't use the escape, it shows up properly when I type it, but disappears in preview and when posted.
> 
> I am relatively new to Github and some of these things seem beyond my ken.

:D backtick esc backtick 

`esc`

**Comment by godbout** [comment]
> This confuses me a bit. Currently, if I am in Normal Mode and hit ESCAPE, that action returns me to insert mode with the highlight still active. Typing 'I' then, just replaces the selection with 'I'.
> 
> I had though earlier of suggesting that 'q' be used to quit kv--that is, leave kv and remove the selection. But it didn't seem very Vimmy. Are you suggesting a separate command that would leave kv and deactivate the selection?

no worries. i'm confused too.

so what i'm proposing is *for sure*:
1. `esc` in Visual Mode goes back to Normal Mode, one character selected (the head of the selection, like Vim)
2. to go to Insert Mode from Normal Mode, you use `i`, `I`, `a`, `A`, `o`, `O`, `c`, `C`, `s` or `S`, as defined by Vim: http://vimdoc.sourceforge.net/htmldoc/intro.html#mode-switching. this will remove the selection, like Vim
3. a kill switch. thinking about `ctrl` `option` `cmd` `J` to go back to Insert Mode while leaving the selection intact so that people can run their macros on it

what i'm not really sure about:
1. allowing people using a Custom Keyboard Shortcut to use it to go back to Insert Mode. i'm afraid that will create bad habits. if allowing, leaving the current solution then, that is you go back to Insert Mode but with the selection still active. so or you use your Custom Keyboard Shortcut deliberately to act on the selection, or you learn that you should use `i`, etc... to go back to Insert Mode, which will keep the Vim habit
2. for people using the default `esc` as a Keyboard Shortcut, i need to allow them to use it to go back to macOS, because it's the only way to send back an `esc` to macOS. in this case i'm not sure yet if i want to remove the selection or not. it's not a problem of habit anymore, it's a problem of sending `esc` to macOS. it's about sending `esc` to macOS, not exiting Normal Mode. but you may not want the selection in this case. not sure.

**Comment by godbout** [comment]
> I had though earlier of suggesting that 'q' be used to quit kv

currently `:q` quits the current application you're on :D

**Comment by tthkbw** [comment]
`esc` `esc` `esc` !! You have created a monster!

I agree with your proposal regarding returning to insert mode from kv. Require a proper Vim command. Remove the capability of returning to insert mode by using a custom shortcut.

**Comment by godbout** [comment]
`hehe`

**Comment by godbout** [comment]
> I agree with your proposal regarding returning to insert mode from kv. Require a proper Vim command. Remove the capability of returning to insert mode by using a custom shortcut.

and then, the ultimate question, what about the ones who use `esc` to enter? back to Insert Mode with `esc` is necessary to send back `esc` to macOS. but keep the selection or not?

to give you an example: you open Alfred, start typing, brain fart, want to leave Alfred. usually you would press `esc`. you do but you enter Normal Mode. another press on `esc` will go back to Insert Mode while sending `esc` to macOS, closing Alfred. in this case, keep or not keeping the selection is the same, but what about in other apps? i would want to leave the selection, to not train the habit to leave Normal Mode with `esc`. but is this what you're complaining about, that it keeps the selection? or where you just talking of `esc` while in Visual Mode? not Normal Mode? aren't you tired of this yet? 😂️

**Comment by tthkbw** [comment]
I don't think you leave a selection active when you leave kv, at least not by default. If you want a separate, special command for that specific purpose, fine, but when you leave kv disable the selection. 

If you want the selection left active, then the only viable reason for entering kv was to do the selection so you can operate on it in the app you are using. This doesn't seem useful to me. What are you going to do with the selection? Delete it? Change it?--then use kv while you have the selection. The only other operation I can think of is to drag and drop it using the mouse? But wait, you have to leave the keyboard and use the mouse to do that, so why not just select with the mouse instead of using kv??

I think leaving the selection when you leave kv is confusing and will really frustrate people, particularly regular Vim users, who are your market. No one expects to enter insert mode in Vim with a selection left lying around.

I am prepared to have you give me a useful example for using kv to select text 😆

**Comment by godbout** [comment]
there's a discussion in #15 about letting non-Vim commands pass through, so that you can run other shortcuts, like for example the [Alfred Universal Actions](https://www.alfredapp.com/universal-actions/). but to let pass everything that Vim doesn't recognize, practically i find it pretty messy. still, people will want to act on the selected text. if not with Alfred, could be to use any of macOS' services: send by email, create an appointment, etc.

**Comment by godbout** [comment]
ok, enough to digest for today. thank you for making kV better!

**Comment by godbout** [comment]
with your `command` `F9`, it should work perfectly now in 1b21. let me know!

**Comment by godbout** [comment]
should be fixed in 1b21 so closing. please reopen if it's still a nightmare.
