### ISSUE TITLE
Electron based apps (e.g. Logseq) doesn't work

### ISSUE THREAD

**Issue by HansPinckaers** [godbout/kindaVim.theapp#38]
Hi,

So I've been trying kindaVim out since beta 12 I think. Then it worked in Logseq / Slab. I tried the different _families_, but that doesn't help sadly. 

`w` and `b` do not jump word-wise, but per character. Also `A` doesn't jump to the end of the line etc.

Thanks for this awesome app btw, will definitely buy a subscription.

Hans

**Comment by godbout** [comment]
yeah supporting Electron apps properly is in the plans but still not done. most probably what happens here is that whatever Input Field Logseq is using is not recognized as a Text Element, so kV applies the Non Text Element Keyboard Strategy. like if it was a dropdown, list etc. i'll try the app and have a look soon.

ultimately i really hope to get the Accessibility Strategy work with Electron apps. that would allow the full kV Vim experience, rather than the key remapping. but the Electron framework doesn't play well with the Accessibility, so it's gonna require a bit more work/time to have a final answer on whether it's possible or not.

**Comment by godbout** [comment]
> Thanks for this awesome app btw

my pleasure.

> will definitely buy a subscription.

wait, not too fast. with payment processing costs i'm finding out that i'll have to raise the price to 3.69US per month. excluding VAT. from the NL it seems it's 21%. that's gonna sting 😅️

**Comment by HansPinckaers** [comment]
Thanks for looking into it, older versions of kindavim did kinda work.

In terms of price; maybe have yearly option as well to cut down on processing cost?

**Comment by godbout** [comment]
> Thanks for looking into it, older versions of kindavim did kinda work.

that's spooky. i'll check within this week and hopefully get something working for the next be'a 👍🏼️

> In terms of price; maybe have yearly option as well to cut down on processing cost?

i like the monthly one. but i checked a few days ago about doing a yearly one yeah. but with two months free. so on my side at the end of the day it's same same. but it's cheaper for the user. so yeah i'm gonna see if it's not too painful to add that option 😀️  i'm a MASTER BUSINESSMAN as everyone can see.

**Comment by godbout** [comment]
> Thanks for looking into it, older versions of kindavim did kinda work.

post-it for myself: https://github.com/godbout/kindaVim.theapp/releases/tag/1b.14
improved the Non Text Element moves in 1b14, which made it worse for Text Elements when the detection fails.

**Comment by godbout** [comment]
i had a look at it's worse than it used to be. maybe a year ago i was able to ping Electron apps through the macOS Accessibility but i would get wrong data. now i can't even ping 😬️ there's some stuff to do to activate programmatically some kind of Accessibility. i'll have a deeper look soon. for next beta i'll add a workaround so that you can use at least the Key Mapping.

**Comment by HansPinckaers** [comment]
Oof. Thanks for looking anyway!

**Comment by godbout** [comment]
no worries. will investigate deeper soon. seems quite a lot of people are using Electron apps.
btw any other of those apps you're using? so that i have a better look. thanks!

**Comment by HansPinckaers** [comment]
Sure, it's mostly for my work: slack, clickup, slab, discord, todoist.

**Comment by godbout** [comment]
ok i've enforced Electron apps to be recognized as Text Elements so i will *kinda* work. it's still Key Mapping so it's funky. and because some moves perform a `return`, you may end up sending a message when you actually want to delete it... 😅️ hopefully better Accessibility support next, or else i'll simplify the Key Mapping moves. please feel free to report any other issue you have. thanks!

**Comment by godbout** [comment]
ok some mixed news:

1. i can enforce the Accessibility for Electron apps 👍️
2. the results are highly depend of the app itself 👎️ (and probably the Electron framework version they're using)
3. it's slow af 👎️ from my tests between 100 and 1000 times slower than native apps. just to turn the AX on i have to loop 3k times to get the Electron framework to acknowledge the AX is on 👎️👎️👎️ but it's still "usable" 👍️
4. Electron apps are restricted 👎️ but kV has the PG-R Mode for that 👍️
5. worse case you put the app in Key Mapping and now kV will see it as Text Element 👍️
6. sometimes it's so slow that moves don't get registered like the undo 👎️ but i'm planning to be alive for the next three days so i may find something 👍️

**Comment by godbout** [comment]
for example Logseq below. works pretty ok. undo doesn't for now (no black cursor back). but you can only work through the current line. you can't go up/down/`gg` etc because of their custom design.

https://user-images.githubusercontent.com/121373/150403198-f799e831-def3-4578-a946-f7616d0c82dc.mp4

**Comment by godbout** [comment]
Clickup would be one where the Accessibility support is pretty bad. so you need to add it to Key Mapping. the moves are not as accurate coz it's just forwarding key presses but no choice. not sure if it's an issue of their custom design, or the Electron framework version they use. but the custom design for sure wouldn't help.

https://user-images.githubusercontent.com/121373/150403739-22f16658-d916-49e0-8633-b11627d740ac.mp4

**Comment by godbout** [comment]
that whole s......tuff will be coming in 1b24 🚀️🚀️🚀️

**Comment by HansPinckaers** [comment]
Wow nice, good work.

**Comment by godbout** [comment]
you're gonna like 1b24. 👀️

**Comment by godbout** [comment]
1b24 OUT 🚀️🚀️🚀️

**Comment by godbout** [comment]
you'll see different results with different Electron apps. some will work with the Electron Family, some will not and will have to be moved to the Key Mapping Family. overall let me know your impressions, frictions, etc.!

**Comment by HansPinckaers** [comment]
So far it works really great! Awesome
