### ISSUE TITLE
text editing wont work in brave browser even after adding it to PG-R

### ISSUE THREAD

**Issue by NikosEfthias** [godbout/kindaVim.theapp#52]
I was folliwing the videos on the youtube channel however I cant get text editing work with brave browser b w etc only move cursor one character at a time

**Comment by NikosEfthias** [comment]
it seems to work now thank you very much for this great app I wish there was a perpetual license option too but also I understand your stand on this being an app developer myself :) have a great day

**Comment by NikosEfthias** [comment]
Actually I did not restart kv after enabling the options and adding brave to the list magically worked @godbout

**Comment by godbout** [comment]
@NikosEfthias but probably once you quit Brave and restart it, it will not work until you restart kV. it's just a guess though. i'll have to investigate on this. (after one restart it would always work.)

**Comment by godbout** [comment]
yes, Brave will always remove those unless you enforce them when launching it with `--force-renderer-accessibility`. dealing with Accessibility is pretty painful, so my goal for kV is to cope with most of those issues without the user being aware of them. which is why kV would enforce those automatically. probably the reason why you need to reenable them manually in Brave now is because kV hasn't been restarted 😅️ that's the issue i'm talking about and that i will look after later.

**Comment by godbout** [comment]
> it seems to work now thank you very much for this great app I wish there was a perpetual license option too but also I understand your stand on this being an app developer myself :) have a great day

oops, missed this.
yeah i understand the wish of a perpetual license, or upgradable licenses. there's two reasons why i'm not doing this though. for the perpetual license it just makes absolutely no sense for me personally. this is a long term project (lots of moves, lots of different environments, apps, situations, etc.). i'm not sure that kV can ever be "finished". that would require implementing every single Vim motions, for every single case. there's no one-time-price i can find that would be worth the effort, time and energy spent on this. on the other side i'm not looking to buy a Lamborghini :D i'm just looking for making enough so that i can work on it full-time (which i've been doing for 1.5 years now 😬️). for the upgradable licenses, i find this too complicated. both as a user, and as a developer. i prefer spending time building kV instead, than dealing with upgrades, marketing, versioning numbers, etc, etc.

that being said, kV is open source: https://github.com/godbout/kindaVim
so nothing prevents anyone to download the source, removing the licensing part, compiling it and using it privately. only reselling is not allowed (official licensing coming later today).

**Comment by godbout** [comment]
no interest :p been riding motorbikes for 20+ years. i'm good with materials, what i need more of is time!

(i'll repeat myself one last time but thanks again for the support. a couple of bucks a month from people who find my work useful or uplifting is worth much more than a bag of money from any shit and useless consultancy work 💫️)

**Comment by godbout** [comment]
issue related to this opened here: issue opened here: https://github.com/godbout/kindaVim.theapp/issues/56
