### ISSUE TITLE
Would be great to be able to switch between workspaces using gT gt and perhaps also apps on the desktop could be considered as splits

### ISSUE THREAD

**Issue by NikosEfthias** [godbout/kindaVim.theapp#53]
basically workspaces would be treated as tabs and individual apps as splits

**Comment by godbout** [comment]
this one is going to be out of kV's scope. at least for now. i haven't explored `gT` and `gt` yet but from what i'm quickly getting it's supposed to be about tabs, not workspaces or splits. that sounds like a personal preference. so that would require some options. the fact to have more options and/or read the `.vimrc` is in the plans, but that's for way later.

i'll investigate and probably add those moves for tabs at first. 
also kV differentiates text inputs that are readable/writable, text inputs that are not, text inputs that are multilines, text inputs that are not, non text inputs, and other UI Elements. but nothing about apps, spaces, etc. that's quite another scope.

**Comment by NikosEfthias** [comment]
I think reading the default vimrc is not a good idea in my case for instance I use lua as my primary config language and that sort of thing would require lots of work on kv end I believe but having a subset of vimrc in .kvrc file would be better option in my opinion

**Comment by godbout** [comment]
that's fair. my bad. i gave the `.vimrc` as an example but that would have to be decided once i dig into this problem. could be a own `.kVrc` yeah, of UI options, or `neovim` plugins. i have no idea for now. i think 3 steps in advance only 😅️

**Comment by godbout** [comment]
alright, had a look. i wasn't familiar with splits and tabs coz i use mainly Vim moves in other editors. Vim just in one tab in the terminal.

> basically workspaces would be treated as tabs

so that one i get it. as explained in the `/` thread though, at least currently, that would need to be done through key mapping, which is not idea. i personally move spaces with `control option command h/l`, but you surely use another binding. should we use the default instead? or probably make this customizable? also why spaces? `gT` `gt` should be for tabs, so it's more of a personal preference? lots of things going on. also using key mapping is pretty not good. would rather use proper Spaces APIs. so that could be an idea, but definitely not possible now.

also, as soon as you leave an input field, kV goes back to Insert Mode. that includes changing spaces. you can't keep Normal Mode across spaces.

> and individual apps as splits

this one i don't get what you mean. something like positioning app windows top and bottom or left and right like splits? (like Windows Management apps like Spectacle or Magnet do.) or using splits key bindings for tabs in apps?

**Comment by NikosEfthias** [comment]
>> and individual apps as splits

> this one i don't get what you mean. something like positioning app windows top and bottom or left and right like splits? (like Windows Management apps like Spectacle or Magnet do.) or using splits key bindings for tabs in apps?

yes, I meant keybindings such that <c-w>l would select the window to the right etc. I am using amethyst with rectangle and even both of them together cannot  really provide the workflow I used to have on i3 on my previous intel mac (unfortunately Linux doesn't seem to be an option for m1 MacBooks)

**Comment by Liquidmantis** [comment]
@NikosEfthias have you seen [Yabai](https://github.com/koekeishiya/yabai)?  I use Yabai, with Hammerspoon to setup my keybindings.

**Comment by Liquidmantis** [comment]
It's not well-commented, but here is my [hammerspoon config](https://github.com/Liquidmantis/dotfiles/tree/main/hammerspoon) in case it helps at all.

**Comment by godbout** [comment]
> yes, I meant keybindings such that l would select the window to the right etc. I am using amethyst with rectangle and even both of them together cannot really provide the workflow I used to have on i3 on my previous intel mac (unfortunately Linux doesn't seem to be an option for m1 MacBooks)

sounds like a total different app is needed to b honest. that's windows management. best kV could do for now would be to map keys. but because there's no windows management by default in macOS, people will use different apps and custom shortcuts. which means you'd need a way to tell kV that *certain* Vim moves should be mapped to something custom. in kV that could probably be done but only once having some sort of kV config file.

not sure if Hammerspoon or Karabiner-Elements could help here. remapping keys before they enter kV is possible. but i don't think the opposite is possible. currently your best bet would be to have Yabai or another alike app handle this, and you'd have to exit kV's Normal Mode first (with the Kill Switch that'd mean one extra keystroke, but better than nothing).

**Comment by godbout** [comment]
config file added to ROADMAP: https://github.com/godbout/kindaVim.theapp#roadmap.

**Comment by NikosEfthias** [comment]
@Liquidmantis tried yabai today but seems not really usable at m1 macs at the moment I really really like the scriptibility of it tho

**Comment by godbout** [comment]
added `gT` (with count) and `gt` in kV12 but to change tabs in any app. the Space thing is a whole other...well...thing.

**Comment by godbout** [comment]
will close for now. not in the roadmap.
