### ISSUE TITLE
search `/` behaviour is weird 

### ISSUE THREAD

**Issue by NikosEfthias** [godbout/kindaVim.theapp#54]
when I hit go into search mode it leaves the search bar open which means you cant go through search results using n N and hit enter to go to focused link. An alternative would be what vimium does, basically its own private search place independent from the browsers or even using browsers search behind the scenes and closing it before keypresses would do the trick I assume

**Comment by godbout** [comment]
i assume you're talking about Brave and Chrome. it works in Safari. this is also something that is (at least currently) out of kV's scope unfortunately. when you're in a readable/writable text input, kV uses the macOS Accessibility and can manipulate text and be very precise. but when you're in a non readable/writable text input or in a UI Element, kV tries its best to get close to Vim moves using key remapping. the issue with Brave and Chrome compared to Safari is that the `shift command f` that is supposed to close the search box doesn't. 

making this work would require or 1) Brave/Chrome handling `shift command f` properly, or 2) handling key remapping PER APP basis (which would require a huge amount of work. this is a long term development so i'm not saying it's not gonna happen, but that would be way down the road) or 3) as you said, do a own private search feature but that's definitely another tool.

**Comment by godbout** [comment]
> even using browsers search behind the scenes and closing it before keypresses would do the trick I assume

i think this is what i'm referring in point 1. i'll make a request to Chrome and Brave and see if they're up to adding this shortcut.

**Comment by godbout** [comment]
i had a quick look. i was wondering why i wasn't using `escape` to leave the search box. here's the reason:

* in Safari, you can search while the box is closed:

https://user-images.githubusercontent.com/121373/156429260-19146e47-5d63-46cb-b370-9aa9d2e14e28.mp4

* in Brave/Chrome, you can't. it will open the box again and focus on it:

https://user-images.githubusercontent.com/121373/156429797-56493281-74dd-47dd-bd83-861be8f65792.mp4

once it focuses on it, the Accessibility Strategy takes over as kV reads the text of the search box:

https://user-images.githubusercontent.com/121373/156430659-2e15729f-9d4d-4569-adbd-6af35c26e4af.mp4

now i need to explain a bit more how kV works. more in the next comment.

**Comment by godbout** [comment]
> now i need to explain a bit more how kV works. more in the next comment.

where kV is gonna be very accurate is in text inputs where i can read and write the text. if it can't read the text or deals with UI Elements, it *remaps keys*, always. it's not calling any extra APIs on an app basis. for example Vimium does what it does because it's a Chrome extension, that has access to Chrome's dev APIs. but from outside you don't. so kV tries its best to "impersonate" Vim, but it's definitely less accurate. i use as much as possible the default macOS keyboard shortcuts first, then the most commons. but it doesn't always work perfectly. 

ok now there's more to it. sometimes apps implement the macOS Accessibility (usually most native apps), some don't (which are then handled through key remapping). but some implement the macOS Accessibility badly (usually Electrons). those apps need to be manually put in one of the `Families`. it can't really be done automatically because kV pings them and ask them if the text is readable/writable and the app says yes, but then give wrong caret locations, selected text data etc. why i'm saying this is because Brave/Chrome implement the Accessibility badly but only in the search box 😅️ see below. when you try to modify the text it doesn't work properly and only deletes the last character. this is because Brave returns wrong data:

https://user-images.githubusercontent.com/121373/156435923-98e9423d-50df-4362-848e-867dee968d34.mp4

so usually the way to deal with those apps is to move them to the `Key Mapping` Family. that will enforce kV to use key mapping rather than reading/writing text. but this is one a **per app** basis. you cannot say "for this field use the Accessibility but for this one use the Keyboard". 

so. if you move Brave in the `Key Mapping` Family, the `/` and `N`, `n` will work:

https://user-images.githubusercontent.com/121373/156436942-247d5f9f-95c5-4ea1-8a44-d28b9b166f79.mp4

but you will lose the most accurate Vim motions everywhere else on Brave:

https://user-images.githubusercontent.com/121373/156437313-50286168-3ffe-43b0-a2b1-1962d733b981.mp4

as you can see in the last one, when the caret is not using a block cursor, that means that kV is using key mapping rather than text manipulation.

up to what you prefer.
i'll still digest and see what i can ask from Chrome/Brave. maybe they could do the search without the showing again the box, etc.

apologies if this is not clear enough. i understand that it's not straightforward. feel free to ask if you have any question.

**Comment by godbout** [comment]
nothing we can do more about this, i'm afraid. if the app supports the macOS Accessibility, we'll do a `/` like in Vim. if not we do through `command f`. that's all we can do.
