### ISSUE TITLE
Adjust size of the thing that shows keys when vimming?

### ISSUE THREAD

**Issue by mrjones2014** [godbout/kindaVim.theapp#63]
I love the feature to show keypresses while vimming as a visual indicator that you're in normal mode, also useful for showing the current command in command mode, but it's a bit large for my taste.

Would you be open to adding an option to adjust the size of it?

I've only been using this app for a day so far and wow is it amazing. I've tried so many other solutions to get system wide vi key bindings (hammerspoon with ViMode.Spoon, Karabiner-elements, etc.) and they all have been very sub-par until this one. Love it ❤️

**Comment by godbout** [comment]
> I love the feature to show keypresses while vimming

wait. is it `Viming` or `Vimming`? 🤔 is there any official term? i've been using `Viming` in the Preferences!

> as a visual indicator that you're in normal mode, also useful for showing the current command in command mode, but it's a bit large for my taste.
> 
> Would you be open to adding an option to adjust the size of it?

absolutely! at the beginning the Characters Window was just for me, for the [screencasts](https://www.youtube.com/channel/UC3ZP3QFMhNn3ivJgqoEW4Ug). after a while i decided to make it part of kV and tweaked it to be proper for release, but that was it.

the philosophy behind kV's development (and all the other things i build) is that i build the bare minimum but always clean, proper and heavily tested. then i can expand/refactor/re-architect if/when needed. so this is just to say that yes, please, send your ideas or the places where you see/feel friction, that you would like to see improved, moves you need etc. whatever. as long as it doesn't go too far from what i intend to do with kV, there's plenty of room for improvement. thanks!

> 
> I've only been using this app for a day so far and wow is it amazing. I've tried so many other solutions to get system wide vi key bindings (hammerspoon with ViMode.Spoon, Karabiner-elements, etc.) and they all have been very sub-par until this one. Love it ❤️

nice. thanks for taking the time to let me know. yeah if you want to have proper Vim Mode for macOS, it's quite the task 😅 Karabiner is fantastic but it's not done for that. you need something specific. the VimMode.spoon is already a great piece. but to get it right (as much as the technology allows) it's dantesque. hence kV being a paid app. hence being a subscription. the project started in Oct 2020. it's been 7 days a week since then (minus some migraines and hangovers). except for the ten days spent trying to do some "serious" marketing, i've loved every minute of it :) thanks for the support!

**Comment by godbout** [comment]
@mrjones2014 out of curiosity, how did you hear about kV?

**Comment by mrjones2014** [comment]
> wait. is it Viming or Vimming?

Lol, not sure, it’s not often I use vim as a verb 😅 

> build the bare minimum but always clean, proper and heavily tested

Love that. One of the things I love most about it is that it “just works” while at the same time, staying out of my way (VimMode.Spoon sometimes got me into weird situations where I’d have to spam escape and `i` like 10 times to get back to insert mode). 

> how did you hear about kV?

I was deep in DuckDuckGo results looking for something better than VimMode.Spoon, I don’t remember exactly but I think it was from Reddit somewhere. When I’m back at my computer I’ll look through my history and see if I can figure it out.

**Comment by godbout** [comment]
> Lol, not sure, it’s not often I use vim as a verb 😅

we can do nouns also. are you a `Vimer` or a `Vimmer`?

> Love that. One of the things I love most about it is that it “just works” while at the same time, staying out of my way (VimMode.Spoon sometimes got me into weird situations where I’d have to spam escape and `i` like 10 times to get back to insert mode).

GREAT! that't the goal. kV and i are working hard so that the end user doesn't have to think too much. in text and wanna go to the top? `gg`. on a webpage in Safari and wanna scroll to the top? `gg`. feels like magic. sometimes probably too much. many people see it as _just_ a small utility tool 😅 double edge sword! but tbh it ends up being less consistent than i would like. that's the grim part of dealing with the Accessibility, and other apps. some implement the Accessibility (fantastic), some don't (ok, can handle), some do it wrongly and send bad data (Electron, very bad). the Accessibility also has quite a bunch of bugs (can't refresh scrolling in browsers TextViews, you'll feel it when a text is too long). even when trying to handle every case, there's that part that is not controllable. 

you reminded me i had some other ideas about the Characters Window also before. like sticking it to the current window that is Viming (one m). maybe some distinction between Normal and Visual Mode. anyways, just dumping here to give myself a little pressure.

> I was deep in DuckDuckGo results looking for something better than VimMode.Spoon, I don’t remember exactly but I think it was from Reddit somewhere. When I’m back at my computer I’ll look through my history and see if I can figure it out.

i see. probably Reddit yeah. i posted kV there a couple of times. got raped each time. PDST for a week after. but seems it's still useful! thank you!

**Comment by mrjones2014** [comment]
>got raped each time. PDST for a week after.

People on Reddit can be... toxic 😅

**Comment by godbout** [comment]
> I've only been using this app for a day so far and wow is it amazing. I've tried so many other solutions to get system wide vi key bindings (hammerspoon with ViMode.Spoon, Karabiner-elements, etc.) and they all have been very sub-par until this one. Love it ❤️

how is it after a week of use? still the same amount of ❤️? 😀️

for the Characters Window, i'm starting working on it. my plan is to have 5 predefined options: smallest, smaller, normal, bigger, biggest. ultimately the text size is linked (currently it's the case too) to some Accessibility settings. so if a user sets all the text in macOS to be smaller or bigger than normal, the Characters Window follows.

the 5 predefined options is a good balance between giving users some flexibility but also not spending ages on something totally custom that may not be that used. let me know if that works for you.

also currently the Characters Window is somehow fixed. you can move it around but then it stays at that place. that includes if you use several monitors. gonna try to improve that. and will check for an option to stick that window next to the current Viming one.

**Comment by mrjones2014** [comment]
> how is it after a week of use? still the same amount of ❤️? 😀️

Still amazing. I did notice one more tiny issue (I can file a separate issue for this), sometimes in normal mode the `b` key moves back by only single letters. I can’t remember if `w` has the same issue or not. I’ll do some more testing. It happens primarily in Slack and sometimes Safari. 

As far as the character window, I think 5 predefined options is totally fine, doesn’t need to be a slider or anything.

**Comment by godbout** [comment]
> Still amazing. I did notice one more tiny issue (I can file a separate issue for this), sometimes in normal mode the `b` key moves back by only single letters. I can’t remember if `w` has the same issue or not. I’ll do some more testing. It happens primarily in Slack and sometimes Safari.

that should mean that kV 1) couldn't read the text so it used the Keyboard Strategy 2) see the input as a Non Text Element. there's different key mappings for Text Element and Non Text Elements. yes can you start another issue for that one? will probably require some explanation about kV, and more info (type of field, App Family, etc.). thanks.

> As far as the character window, I think 5 predefined options is totally fine, doesn’t need to be a slider or anything.

👍️ (gonna probably be a slider though 🎚️)

**Comment by godbout** [comment]
how does that look:

https://user-images.githubusercontent.com/121373/163724840-4ff33daa-d037-4be8-bd35-8182f699d363.mp4

as said earlier, i don't want to make this fully customizable. so 5 sizes. but well, quite subjective.

**Comment by mrjones2014** [comment]
That looks perfect, that’s more than enough options, thanks!!!

**Comment by godbout** [comment]
still some stuff i'm gonna tweak regarding that Characters Window. but should be out by the end of the week.

**Comment by godbout** [comment]
kV18 out: https://github.com/godbout/kindaVim.theapp/releases/tag/18

**Comment by godbout** [comment]
sticking the Characters Window on top of the Viming input (rather than window) should come in Part 2. also showing the Vim Mode rather than characters type. also some fine-tuning, probably of the text, padding, etc.

**Comment by godbout** [comment]
does that make sense to have an option to get the Characters Window to follow the block cursor? 🤔

https://user-images.githubusercontent.com/121373/164889638-06d858a3-a310-4cc0-be35-aee7c3fedd92.mp4

️

**Comment by mrjones2014** [comment]
Hm, I don't think I'd use that feature personally. I'd expect it to be pinned in the corner.

**Comment by godbout** [comment]
> I'd expect it to be pinned in the corner.

that one is coming in Part 2. (kV19). will be on top of current input. same as window, but for inputs.

**Comment by godbout** [comment]
kV19 out: https://github.com/godbout/kindaVim.theapp/releases/tag/19

you can now have the Characters Window above the current Vim input, rather than Vim window.

if all good i think we can close this one? feel free to open another issue if you've got more requests.

**Comment by mrjones2014** [comment]
Perfect. Looks awesome. I like the "above the viming window" option paired with the "vim mode" option for what to display in the window. 

Go ahead and close. I'm satisfied. 🎉
