### ISSUE TITLE
Sometimes move by word doesn't work

### ISSUE THREAD

**Issue by mrjones2014** [godbout/kindaVim.theapp#64]
sometimes in normal mode the b key moves back by only single letters. I can’t remember if w has the same issue or not. I’ll do some more testing. It happens primarily in Slack and sometimes Safari.

Will fill out more details when I'm back on my mac.

**Comment by mrjones2014** [comment]
It was actually Signal that was having this issue, because it's an Electron app. Adding it to the Electron family fixes it.

**Comment by godbout** [comment]
@mrjones2014 👍️ i was gonna answer and direct you to there first, yes. dealing with Electron apps is where things are gonna be a bit less smooth, unfortunately. different Electron apps use different version of the Electron framework, then some implement the accessibility properly, some don't (like Slack). so the first thing is to move those apps in the `Electron Family` like you did. if it's still funky, then you need to move them to the `Key Mapping Family` where it's using key remapping to do the Vim moves. so not was many or as accurate as usual, but better than nothing. those steps have to be done manually somehow because Electron apps are slow, and their accessibility is even slower (like 3k times slower than native apps), so doing it automatically would slow down the whole kV. the current manual `Families` is the best balance i've found currently.

**Comment by godbout** [comment]
> Generally that's true but not as a general rule. Electron apps are typically slow because the apps that use them are typically poorly architected around Electron as a core (which is isn't meant to be -- it's meant to be a UI framework only).

true. i've been spending too much time with the Accessibility so that's how i judge Electron apps now 😂️
 
> Plugging the 1Password 8 desktop app (since I work at 1Password 😄), which is built with Electron but uses it only as a UI framework, the app core is all in Rust native code, and it definitely stands out among Electron apps. It uses literally 0.0% CPU at idle and only like 50 MB memory at idle. And on top of that, kindaVim works in 1Password 8 without even adding it to the Electron family 😁

![ColossalWelloffBlacklemur-max-1mb](https://user-images.githubusercontent.com/121373/162743498-f6553c8d-a2e7-4bec-bf0b-a99c9c43bcd3.gif)

i tried the beta in August i think? when it came out. i don't think kV was working with it at that time. actually i'm not gonna lie, i was pretty upset 😅️ i love 1Password. bought and now subscribed for ages. the fact that it was a native app, compared to all the other Electron ones, was a mega plus for me. tried the beta when it came out and i reverted back to 7 quickly. read the blog posts, also the forums. i understand the move but i was still IN SHOCK 😂️ tho i'll move to 8 when it's released so, i'll have to deal with it. thanks for testing kV with 1Password 8 for me in advance then 😀️

**Comment by godbout** [comment]
> 3) keyboard focus

that was an issue for me also. i like to be able to do almost anything with the keyboard. tbh i think it's the 1Password for Safari that has been updated also and it shows the list of logins available and it put me off. pretty sure i could disable this and/or change my habits (seems kV can go down the list) but i didn't take the time to research yet. until now i've always used 1Password with Alfred. auto opening of browsers and filling the info. so nice. still, excited about how it's gonna turn out with 1Password 8. as far as i'm concerned nothing comes close.

(btw, `jk` on the way. if nothing goes awry it'll be out this week, experimental first as i'll need you and the other person's feedback to see which way to fine-tune. will also add delay configuration later. Characters Window has to wait a bit. had a try but need to upgrade my SwiftUI skills first.)

**Comment by mrjones2014** [comment]
Awesome! Super excited to have `jk`

**Comment by godbout** [comment]
ok you got me excited with 1Password 8 😀️

i've reinstalled the beta. got some issues at first but seems it was because i still had 1Password 7 on my Mac. there's still gonna be two things that will be hard for me. one is very subjective: it doesn't feel Mac to me. the Settings, the checkboxes, etc. the second thing is going to be harder: no Accessibility available. this is one big ScrollArea. i'm building another app to reach anywhere in macOS through typing on your keyboard. like kindaVim, it uses the Accessibility but differently. it's pinging every Accessible object. it works with 1Password 7, it does not work at all with 1Password 8 because it can't ping any (native) object. tough. will drop by the forums once it's out of beta 😅️

**Comment by mrjones2014** [comment]
As far as I know, several of the "non native feeling" things are being worked on for the stable release.

My favorite feature of 1Password 8 is the ability to use it as my SSH key generator, and my SSH agent (so, the SSH keys don't even have to be stored on disk), which gives you the ability to authenticate with Apple Watch for SSH requests. I'm also using the 1Password CLI to authenticate `sudo` requests with Apple Watch. Gives me such a spark of joy 😁

**Comment by godbout** [comment]
> As far as I know, several of the "non native feeling" things are being worked on for the stable release.

i've posted on the forum. let's see. but even though i'm sure something can be done on the UI, i have doubts about the accessibility...

to show you the big issue i'll have now:

https://user-images.githubusercontent.com/121373/162804228-087c9a57-9fbf-4f65-901d-14cad39a0234.mp4

in 1Password 7 i can ping anything and send the mouse there and click. in 1Password 8, it's all gone. i get that it's not the most common use case. but that means that all the people depending on VoiceOver and other Screen Readers (including disabled people) will not be able to use 1Password 8... anyways, not gonna bother you more with that 😬️😅️ thanks for your time on this.

> My favorite feature of 1Password 8 is the ability to use it as my SSH key generator, and my SSH agent (so, the SSH keys don't even have to be stored on disk), which gives you the ability to authenticate with Apple Watch for SSH requests. I'm also using the 1Password CLI to authenticate `sudo` requests with Apple Watch. Gives me such a spark of joy 😁

yeah saw that one, the SSH. was wondering how i could use it in my case, as i'm actually through a GPG SSH key. will dig later. when i've finished kV. so in 2049.
