### ISSUE TITLE
implement `gx` key mapping

### ISSUE THREAD

**Issue by mrjones2014** [godbout/kindaVim.theapp#69]
Feel free to close if this isn't really feasible, it may not be. I have no idea how the accessibility APIs work.

But it would be cool to be able to use `gx` to open the URL under the cursor.

**Comment by godbout** [comment]
had no idea about this :D

i have access to the underlying text, caret position etc etc so clearly doable, even though it's different from the usual moves. sounds fun.

checked through the Vim doc tho and it's not really like an "official" move? do you know a bit? is it part of some integrated plugin or  something similar? just to know how i would incorporate this within kV's architecture. thanks!

**Comment by mrjones2014** [comment]
It's not really a "move" it's just a keybinding that grabs the word under the cursor and attempts to open it with an external program. I think on MacOS it just uses `open` for the most part, so for `http(s)` URLs open in browser, `file://` URLs open in Finder, etc.

I think it's part of `netrw` which is a built-in "plugin" that ships built-in with Vim/Neovim.

**Comment by mrjones2014** [comment]
See `:h gx` in Vim/Neovim.

**Comment by godbout** [comment]
yeah i checked in Dash but i didn't really understand that `netrw` thing at first, which is why i asked if it was some sort of builtin plugin. coz i don't want to add (at least not at first) specific plugins. if i do one day, it'll have to be more of a system of loading already like neovim existing plugins i guess. but if `gx` is builtin then fuck yeah let's do it.

though at first i thought it was just web URLs, not files etc. will need to check how macOS handles this. might be more complicated than expected, but surely doable.

**Comment by godbout** [comment]
i'll research more after i've handled a few other things first.

but imagine i add it and people love it and can't stop using it but in your case kV gets even worse and it only works like two days a week LOL. that would be kinda funny.

**Comment by mrjones2014** [comment]
lol. the frustrating part about #66 is that I can't even reproduce it, I just have to wait for it to randomly happen. Still stable and going strong since we last chatted there.

**Comment by godbout** [comment]
yeah man, sorry about that. i'd like to pinpoint also the issue, so that at least, even if it's not from kV, we can not just close the issue but TOTALLY DELETE it.

although if hammerspoon works, it has to be somehow related to kV... anyways, we have the logs now. and i keep a git branch with them, so we can keep narrowing the issue.

**Comment by godbout** [comment]
that's also possible that adding the logs is just making your laptop behave differently. now that it knows it's being observed. you know, like the quantum double slit experiment, particle and wave blah blah.

**Comment by godbout** [comment]
kV20 out: https://github.com/godbout/kindaVim.theapp/releases/tag/20

a few things regarding `gx`:
1. because this requires having access to the text, it works only in inputs where we can use the Accessibility Strategy. that means in most native apps, and apps in the `PG-R` and `Electron` Families. it will not work with apps in the `Key Mapping` and `911` Families, as those ones use key remapping instead of text manipulation
2. it's done for Normal Mode and Visual Mode
3. the detection of links is a bit harder than expected (as always). like for example a `[` is not valid in a web URL without being encoded, but it is in a file URL. there's surely many cases that have to be handled, but currently i've handled only a few. still, i think that should take care of at least 80% of the cases. if you encounter cases where it doesn't work, please let me know and i'll handle them (all backed by tests, so easy to improve in the future)
4. it's fun

**Comment by mrjones2014** [comment]
Used it a bit today, it works pretty well with the caveats you already mentioned above.

Tangentially related, Firefox based browsers have to go into the 911 family :(  which is pretty surprising. I’m just curious what browser you use primarily? Chrome seems to work, but I thought Firefox had pretty good accessibility too, but maybe I’m wrong.

**Comment by godbout** [comment]
> 911 family

can't believe i came up with such a great name tho. makes me lol every time someone writes it down.
 
> Tangentially related, Firefox based browsers have to go into the 911 family :( which is pretty surprising. I’m just curious what browser you use primarily? Chrome seems to work, but I thought Firefox had pretty good accessibility too, but maybe I’m wrong.

i use Safari on a day-to-day basis, Brave for web dev. Chromium based browsers (as well as Electron apps) need a special Accessibility attribute to be set programmatically in order to enable the AX. i haven't dug much into Firefox but i do remember people complaining about their AX features. i'll dig more. if `gx` is good, let's close this issue and open a new one regarding Firefox and Accessibility in general?

**Comment by godbout** [comment]
ok so i've spent some time with Firefox (v100) and on plenty of pages and broken links on their sites and i still can't find how to activate the AX. many outdated help pages and broken links. this is pretty disgraceful.

**Comment by godbout** [comment]
> 

i've typed this in Firefox hehe.

**Comment by godbout** [comment]
> ok so i've spent some time with Firefox (v100) and on plenty of pages and broken links on their sites and i still can't find how to activate the AX. many outdated help pages and broken links. this is pretty disappointing.

what's your plan with Firefox? is it your daily browser?
i got 10% working on older versions, but not on v100. but basically it's broken. to activate the AX it's not even custom stuff like Electron or Chromium, it's custom customed. would need to handle Firefox separately. and after the AX is activated, it's not even working properly. like changing/deleting doesn't occur on the right part of the selection. could be because the AX in Firefox is too slow. could be because like most Electron apps they returned wrong data. i didn't dig further. Electron apps can be put in `Key Mapping` because i handle their custom AX activation, but i don't for Firefox, so it has to be put in `911` instead. as far as i'm concerned there's not gonna be, at least in a short time, a per app basis support. that would be madness. i'm trying to handle most cases but when an app decides to go around Apple's APIs and do their own custom stuff, then they're on their own (means `911`).

**Comment by godbout** [comment]
ok so as usual that's gonna bug me so i'm gonna look more into it in the following days ☹️

**Comment by godbout** [comment]
moves the Firefox issue to #70.

**Comment by mrjones2014** [comment]
Yeah I use Firefox primarily for work and LibreWolf (a privacy and security focused fork of Firefox) for personal stuff. 

We can close this issue for `gx` though.

**Comment by godbout** [comment]
alright. will check then. thanks for all the work ☹️😂️

the next big feature will be some sort of wizard. thinking you drop your app and it gives you a summary, and tells you in which Family to put your app. every app will have to be tested manually by me first. so i'm adding Firefox and LibreWolf to the list!

**Comment by godbout** [comment]
update on #70. i can't ping you there.
