### ISSUE TITLE
up/down navigation using ctrl j/k like VSCode Vim

### ISSUE THREAD

**Issue by lougreenwood** [godbout/kindaVim.theapp#74]
I use KindaVim & VSCode.

In VSCode I use the [VSCode Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) addon, so I disable VSCode in KindaVim.

VSCode Vim has a nice feature which allows navigating lists using ctrl j/k keys _without having to enter normal mode_ I find this essential and it's become part of my muscle memory for interacting with app menus.

It would be nice if KindaVim offered something similar. When interacting with system UI I find that needing to drop back to normal mode to navigate a list - whilst strictly correct for Vim / modal editing - feels like a hinderance for fast UI interaction.

What do you think?

**Comment by godbout** [comment]
i see your point but this is gonna be out of scope, sorry. kindaVim is not going to remap keys outside of Normal Mode, except for entering that mode itself. usually it's already quite a big no no to remap macOS keys. in your case this is very specific to your own habit, so that would need to be an option but kV is definitely not the right tool.

for that you can use a key remapping tool. there's plenty of free, open source tools to do that, like [Karabiner-Elements](https://karabiner-elements.pqrs.org) or [Hammerspoon](https://www.hammerspoon.org). with those tools you can just remap `ctrl j/k` to `up/down`.

also not sure if you know about it, but by default macOS comes with `ctrl n/p`, although that differs from your habit. but most apps work with that combination out of the box, while it's not the case with `ctrl j/k`.

**Comment by godbout** [comment]
closing as will not implement.
