### ISSUE TITLE
`o` / `O` don't work properly in normal mode

### ISSUE THREAD

**Issue by lougreenwood** [godbout/kindaVim.theapp#75]
I use `o` / `O` a lot in normal mode for working with prev / next lines.

It seems that in KindaVim `o` doesn't insert a line below and `O` highlights the line above if it has content.

Here's a screen recording: https://monosnap.com/file/itm9KVzgG03h7who2fpbnzGQtnsFGd

In the screen recording you'll also see that `o` and `O` are shown as `I` inputs, so maybe KindaVim just doesn't support these keys yet?

**Comment by godbout** [comment]
> I use `o` / `O` a lot in normal mode for working with prev / next lines.
> 
> It seems that in KindaVim `o` doesn't insert a line below and `O` highlights the line above if it has content.
> 
> Here's a screen recording: https://monosnap.com/file/itm9KVzgG03h7who2fpbnzGQtnsFGd
> 

there are some apps that are "restricted". Safari is one of them. as far as the macOS Accessibility is concerned the change worked, but in reality it didn't. so you need to manually add Safari in the `PG-R` Family. you can drop apps to The Wizard in the Preferences when an app doesn't work like you would expect to get an idea of why and in which Family to put the app.

![Screen Shot 2022-05-27 at 18 44 45](https://user-images.githubusercontent.com/121373/170685415-5ce20189-71f2-499d-a599-fbee48604aed.png)

technically when you put an app in the `PG-R` Family, kindaVim uses the macOS Accessibility to "calculate" the caret position, the selection, how the text needs to be manipulated, but ultimately uses key remapping to delete or paste text. for the end user it looks the same, but those apps need to be added into that Family.

> In the screen recording you'll also see that `o` and `O` are shown as `I` inputs, so maybe KindaVim just doesn't support these keys yet?

those are both supported for the Accessibility Strategy (https://github.com/godbout/kindaVim.theapp#kv-accessibility-strategy-text-manipulation-accurate) and the Keyboard Strategy (https://github.com/godbout/kindaVim.theapp#kv-keyboard-strategy-keyboard-remapping-less-accurate). the Characters Window shows `I` because kV is supposed to go back to Insert Mode. it doesn't yet in your case because Safari is not in the `PG-R` Family. once added there it'll all work.

let me know if this is not clear and if that answers your issue.

**Comment by lougreenwood** [comment]
Thanks a bunch @godbout - this worked as expected 👍
