### ISSUE TITLE
add Discord.app

### ISSUE THREAD

**Issue by dbalatero** [godbout/kindaVim.theapp#83]
(to the wizard!) I suspect it's Electron, similar to Slack.

**Comment by godbout** [comment]
ha! forgot that one. will add for kV23, thanks.

btw i'm gonna simplify the `Keyboard Strategy` for `Text Elements` soon, probably for kV24. i'm not myself using much Electron messaging apps but i've found when doing testing for The Wizard™ that several moves could be triggering sending the message, coz they're including the `return` key. usually it's because i copy the linefeed for next pastes. but i'm going to try to improve this. i think i should be able to ignore the linefeed, and only add it or remove it depending on the context (Visual Style) when pasting. if i can do that, all the Electron apps like Signal, Whatsapp, Slack, Discord etc. should behave better ultimately.

**Comment by godbout** [comment]
i'm pushing Discord to kV24 actually, sorry. the `Electron` Family doesn't work, so the AX doesn't work with Discord, but i want to research why first, and i'm planning a release in a few hours, so no time for now. the `Key Mapping` Family is "working" but as said in the previous comment, some moves will trigger sending the message, which you probably don't want. so i'll pack Discord and the Keyboard Strategy update for kV24.

**Comment by dbalatero** [comment]
All sounds good! Thanks!

**Comment by godbout** [comment]
added in: https://github.com/godbout/kindaVim.theapp/releases/tag/24

1. issues regarding the macOS Accessibility reported to Discord as: # 25553359
2. issues regarding `shift control e/a` that affects the Keyboard Strategy reported to Discord as: # 25553501

**Comment by godbout** [comment]
Discord acknowledged the issues. will update (or create a new thread) once they fix.

**Comment by godbout** [comment]
so Discord is pretty funny. once a week they're sending an email telling me they haven't looked at the issues and they're gonna close because they believe the issues have fixed themselves. so if i don't respond to the email they're closing the support ticket. wtf lol

**Comment by godbout** [comment]
so they sent an email again. asking me to try again. same version. same error. seems they're sending an email every two weeks until i stop answering, and then they'll close the issue without fixing anything.
