### ISSUE TITLE
Warn users when they haven't categorized an app

### ISSUE THREAD

**Issue by dbalatero** [godbout/kindaVim.theapp#84]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/59429/171970331-88320fdb-7538-4e5a-a0c8-b3beb76fffa2.png">

I wonder if you could warn users here when they focus an app they haven't categorized yet?

**Comment by godbout** [comment]
yes!

i've been thinking about this, but i haven't been able yet to come up with a proper solution. here's my current train of thoughts:

# things to think about
* lots of apps will not need categorizing
* want to avoid a long, wide menu
* The Wizard is probably the way to go in any case, rather than adding directly to a Family

# potential solution
* add something in the status menu like: ""Discord" not working properly?" and then have a submenu.
* submenu with only one item (? weird) like "send it to The Wizard!"
* open the Preferences window, Families tab

the last point is where i got stuck in maybe a first implementation. i can open the Preferences window programmatically, but not focusing on the Families tab. although now that i'm typing this, i'm thinking that should/could be done through AppleScript...

what do you think? please point where my assumptions may be wrong, and if you have any other/better idea, and how you would feel as a user.

forgot if i updated you on the "scanning the Application folder" thing. i thought about it, but i think it would be extra confusing. and also extra work. like if there's this feature, probably you're gonna scan once in a while rather than adding specific apps. but what should be done with apps that are already in Families? what about the ones you know don't need to be categorized? do you want to see them when you scan? no? maybe later? too many possible options. and i don't think it's necessary. if someone wants to scan the whole folder, makes more sense to drop all the apps one time, at first. then to add one by one, when one has issues.

**Comment by godbout** [comment]
gonna close this now that we have the new menu system to add apps, starting with kV24.
