### ISSUE TITLE
Allow disabling apps that don't have a draggable icon

### ISSUE THREAD

**Issue by Kyle-Mendes** [godbout/kindaVim.theapp#86]
For example, when streaming a game from my PC, the app is `steamstreamingclient` in the Activity Monitor, but I don't have anything to drag.  Disabling `steam` doesn't work either.

It would be great if I could disable this somehow.  Perhaps with a name match?

**Comment by godbout** [comment]
i have 0 experience with streaming, stupid question incoming: so the streaming is running through Steam?

currently personally if i run something from Steam i just quit all apps, including kV. kV needs to listen to keystrokes to know if you're asking to enter Normal Mode. it doesn't take resources, but my MBP is so dying already when i'm playing something that i quit everything :D

kV checks what's the frontmost app, because this is where it executes Vim moves. i'll research what's the frontmost app when Steam is running games or something. i guess there's gonna be a way yes, even through the process name. just gonna make things a bit more complicated, and need to find a good UI for that. but that should be possible. will keep you updated.

**Comment by Kyle-Mendes** [comment]
Yep! The setup works like this:

1. Have Steam open and have game installed on another computer (Let's call it Windows PC)
2. Have steam open on Mac
3. On Mac, go to a game _not installed_ and click `Stream`
4. Game will open on Windows PC
5. Steam opens a new app that streams the content of Windows PC to Mac and feeds inputs from Mac to Windows PC

It allows you to play games you own, but can't play on Mac, on your Mac!

The app that opens is called `steamstreamingclient`

This might have more information about how it works: https://help.steampowered.com/en/faqs/view/0689-74B8-92AC-10F2

**Comment by godbout** [comment]
and me like a peasant who just play on the Mac and see my Windows game with a little ❌️ next to it ☹️

ok i'll research. using the name though is kind of a no no, coz they're not unique. the bundle IDs are, which is why i'm using those instead. anyways, i'll investigate and update.

**Comment by godbout** [comment]
> > using the name though is kind of a no no
> 
> Definitely. It could potentially be added as like a "not recommended" section to do last-ditch efforts of ignoring things that don't have easy ignores, as well!

yeah, i wasn't planning to change the whole engine 😅️

when you stream does it have to be fullscreen? or can it be a window on the Mac where kV is? if it's the case i have some good idea i think 💡️ combining your issue with something else i was thinking about. oh i'm so excited already.

**Comment by Kyle-Mendes** [comment]
When I stream right now, it automatically full screens.  I don't know of a way (currently) to _not_ have it be fullscreen.

**Comment by godbout** [comment]
alright, i'll investigate more tomorrow.

i've tried here with two games from Steam. you can't drop the apps because they're not real apps, they don't have a bundle identifier. but once the games are launched, they have to have an identifier. so i just pull them out of fullscreen (through their options), and i can run kindaVim on them and get the bundle identifiers. what i'm thinking about is adding the current app in the status bar icon (menu). from there you could send it to The Wizard, or add it to any Family, etc. this is something i was pondering about already, but that would solve the problems of apps without icons.

**Comment by godbout** [comment]
i've added something for kV24. in the status item bar, in kV's menu, you'll see the detected frontmost app. from there you can disable it (or send the app to The Wizard). that allows to disable (or more) apps that don't have a draggable icon, or an invalid one. (like the Steam games fake apps.)

https://user-images.githubusercontent.com/121373/172393563-ff74eb4a-7587-49e1-ac68-1d35f99e8b60.mp4

so all you need now is to exit fullscreen mode when you stream, go through the menu, disable the Steam streaming app, and you're done. only need to be done once. let me know if that'd help.

**Comment by Kyle-Mendes** [comment]
That's awesome! I'd love to try it out. I think that would help a lot :D 

I'll need to try it with some games that don't have the ability to disable full screen from within the game (some very old games), but this should be great for the majority of use cases, I think!

(There could be another option, where there's a keyboard shortcut to add the currently focused app to the off list as well, if it's not possible to get to the status bar.)

**Comment by godbout** [comment]
kV24 should be coming tomorrow. feel free to update me later if this doesn't help.

**Comment by godbout** [comment]
out: https://github.com/godbout/kindaVim.theapp/releases/tag/24

**Comment by Kyle-Mendes** [comment]
Thanks for adding this!  Unfortunately, the app I'm using can't get the mac context bar :(

I've been trying lots of different ways, but it's not popping up.  It's forced into full screen mode and overrides both hovering the top of the screen as well as keyboard commands (since it's pushing it to the steam computer).

This might be quite the edge case though.  I can just keep turning of Kinda Vim when I stream this game :)

**Comment by godbout** [comment]
so is this this app?: https://apps.apple.com/us/app/steam-link/id1246969117

or do you just have Steam logged in on both computer and go through there?

**Comment by godbout** [comment]
i have a second laptop but the SSD is dead, so to test i'll need to install macOS through an external HD. gonna take ages.

**Comment by godbout** [comment]
maybe that helps? https://help.steampowered.com/en/wizard/HelpWithGameIssue/?appid=353380&issueid=351&nodeid=47

**Comment by Kyle-Mendes** [comment]
It's weird. I'm actually using the game in windowed mode on the host machine, but it's full screen on the mac.

I'm going through steam for both computers.

**Comment by godbout** [comment]
ok so i set it up and the bundle identifier for the Steam streaming client is "com.valvesoftware.steam.streamingclient".

**Comment by godbout** [comment]
i've added the Steam streaming to list of special exceptions. kV will ignore it automatically, starting from kV25. i doubt that someone will ask kV to work with it 😅️ if someone really does, and it makes sense, then i'll think of a better solution.

**Comment by godbout** [comment]
kV25 out: https://github.com/godbout/kindaVim.theapp/releases/tag/25
the Steam streaming will be automatically ignored.

**Comment by Kyle-Mendes** [comment]
Thank you so much! <3

**Comment by b11e** [comment]
Is there a way to disable in a config file somewhere? There are apps that are not draggable. For example most if not all steam games cannot be dragged. 

Actually it would be great to have a whitelist instead of a blacklist

**Comment by godbout** [comment]
> Is there a way to disable in a config file somewhere?

currently nope. 1) couldn't find a way that felt right regarding UI/UX 2) hasn't seem to be an issue big enough to bump the priority. but maybe a config file may be a solution. hmm. in the TODO and will digest.

> There are apps that are not draggable.

any concrete example? i'm a very, very casual player, like i play one game every two years when i need a break from coding, but pretty sure most Steam games are draggable, or can be added when they're running?

 see videos below.

> Actually it would be great to have a whitelist instead of a blacklist

so do you mean that when you install kV at first it just doesn't work on any app at all? and people would have to discover what and why Families are there right from the start? the notion of the Families is somehow necessary due to macOS, and due to the nature of kV, but i think it's better to bring it little by little when people are experiencing issue with the current app they're using, rather than blacklisting everything from the start. or am i missing something? they used to be a master kill switch also to disable kV completely until reactivation, but again it ultimately didn't seem to be useful. at least not for apps as really, 99% of them seem to be draggable?

add Steam games through the app bundle:

https://github.com/user-attachments/assets/21d67c0b-35fc-4937-897d-40f7d41bbf01

add Steam games from kV's menu bar icon:

https://github.com/user-attachments/assets/f73aa2a8-f410-4a2a-b0ff-4befca024726

**Comment by b11e** [comment]
https://github.com/user-attachments/assets/849cf785-4009-43f7-a341-d9aa6ee16bba

**Comment by b11e** [comment]
> > Is there a way to disable in a config file somewhere?
> 
> currently nope. 1) couldn't find a way that felt right regarding UI/UX 2) hasn't seem to be an issue big enough to bump the priority. but maybe a config file may be a solution. hmm. in the TODO and will digest.
> 
> > There are apps that are not draggable.
> 
> any concrete example? i'm a very, very casual player, like i play one game every two years when i need a break from coding, but pretty sure most Steam games are draggable, or can be added when they're running?
> 
> see videos below.
> 
> > Actually it would be great to have a whitelist instead of a blacklist
> 
> so do you mean that when you install kV at first it just doesn't work on any app at all? and people would have to discover what and why Families are there right from the start? the notion of the Families is somehow necessary due to macOS, and due to the nature of kV, but i think it's better to bring it little by little when people are experiencing issue with the current app they're using, rather than blacklisting everything from the start. or am i missing something? they used to be a master kill switch also to disable kV completely until reactivation, but again it ultimately didn't seem to be useful. at least not for apps as really, 99% of them seem to be draggable?
> 
> add Steam games through the app bundle:
> 
>  Screen.Recording.2025-03-20.at.22.36.07.mov 
> add Steam games from kV's menu bar icon:
> 
>  Screen.Recording.2025-03-20.at.22.36.54.mov

sent videos above
There might be something about the type of shortcut that is draggable?
Maybe for adding a program through the menu you could pick from a list of detected windows. I'm not sure what's more feasible or easier as I'm not familiar with mac system apis since i'm guessing macos can have really annoying "security" features that block access to basic things

yes configuring through a simple text file works with me. can be lua, toml, yaml, or plain text. whatever works. 

I prefer a whitelist but I understand how that would be annoying upon first installation for some. If I could just have it ignore everything under a certain directory so I can have it ignored for all steam games that would be nice. Or have that by default that would be fine with me.

**Comment by godbout** [comment]
@b11e do you mind ultimately opening a new issue so that we can keep track? thanks.

**Comment by godbout** [comment]
also for reference, might be worth checking https://github.com/godbout/kindaVim.blahblah/issues/203

shows there's a bunch of more complicated stuff happening behind the scenes, with app bundles, shell environment variables etc.

**Comment by godbout** [comment]
found a game of mine that doesn't work either. neither through the icon being dragged, nor the window. the issue is actually not with the window, the issue is that in order for kV to know what app it's dealing with, it needs its bundle ID. that game doesn't have any bundle ID set. it should be a big no no in the macOS world, but it does happen with this game. i guess it's the same with yours? in that case there's nothing to do, because kV can't know what kind of app it's getting activated onto. one thing that could be changed is that if there's no bundle ID found, then kV goes to Off automatically? but that would break people's expectations, i think. lack of consistency. why suddenly kV wouldn't respond while the user did nothing for that to happen?

to check whether your game has a bundle ID or not, run this from your terminal: `osascript -e 'id of app "Safari"'`
replace `Safari` with the name of the game, or the app bundle, etc. for The Talos Principle what i get back is literally: `????`.

**Comment by godbout** [comment]
from the debug:

```
<NSRunningApplication: 0x600002510b80 (com.valvesoftware.steam - 63769) LSASN:{hi=0x0;lo=0x157c57b}>
<NSRunningApplication: 0x60000251cb00 (com.valvesoftware.steam.helper - 63786) LSASN:{hi=0x0;lo=0x157e57d}>
<NSRunningApplication: 0x600002518b00 ((null) - 80766) LSASN:{hi=0x0;lo=0x17e37e2}>
```

launching The Talos Principle. Steam gets launched, then Steam helper, then Talos without a bundle ID, so no way for kV to know what app it is on.
